# Generated by Django 4.2.5 on 2023-09-30 16:18

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("products", "0003_alter_product_image_large"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductAmount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.SmallIntegerField(
                        help_text="Specify the number of products.",
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="amont",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        help_text="product",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="product_amounts",
                        to="products.product",
                        verbose_name="product",
                    ),
                ),
            ],
            options={
                "verbose_name": "product amount",
                "verbose_name_plural": "product amounts",
            },
        ),
        migrations.CreateModel(
            name="ShoppingCart",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        help_text="Shoping cart owner",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shopping_carts",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="customer",
                    ),
                ),
                (
                    "product",
                    models.ManyToManyField(
                        help_text="Add to shopping cart",
                        related_name="shopping_carts",
                        through="orders.ProductAmount",
                        to="products.product",
                        verbose_name="product",
                    ),
                ),
            ],
            options={
                "verbose_name": "shopping cart",
                "verbose_name_plural": "shopping carts",
            },
        ),
        migrations.AddField(
            model_name="productamount",
            name="shopping_cart",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="product_amounts",
                to="orders.shoppingcart",
                verbose_name="shopping cart",
            ),
        ),
    ]
