# Generated by Django 4.2.5 on 2023-10-02 10:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="shoppingcart",
            name="unique_customer_products_together",
        ),
        migrations.RenameField(
            model_name="shoppingcart",
            old_name="products",
            new_name="product",
        ),
        migrations.RemoveField(
            model_name="shoppingcart",
            name="amounts",
        ),
        migrations.AddField(
            model_name="shoppingcart",
            name="amount",
            field=models.SmallIntegerField(
                default=1,
                help_text="Product's amount",
                validators=[django.core.validators.MinValueValidator(1)],
                verbose_name="amount",
            ),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name="shoppingcart",
            constraint=models.UniqueConstraint(
                fields=("customer", "product"), name="unique_customer_product_together"
            ),
        ),
    ]
