# Generated by Django 4.2.5 on 2023-09-30 08:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0003_alter_product_image_large"),
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="shoppingcart",
            name="product",
        ),
        migrations.AddField(
            model_name="shoppingcart",
            name="product",
            field=models.ManyToManyField(
                help_text="Add to shopping cart",
                related_name="shopping_carts",
                to="products.product",
                verbose_name="product",
            ),
        ),
    ]
