# Generated by Django 4.2.5 on 2023-09-28 14:40

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Category's name",
                        max_length=150,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator("[А-ЯЁа-яё, ]+$")
                        ],
                        verbose_name="name",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(help_text="Category's slug", verbose_name="slug"),
                ),
                (
                    "image",
                    models.ImageField(
                        help_text="Category's image",
                        upload_to="media/category",
                        verbose_name="image",
                    ),
                ),
            ],
            options={
                "verbose_name": "category",
                "verbose_name_plural": "categories",
            },
        ),
        migrations.CreateModel(
            name="SubCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Subcategory's name",
                        max_length=150,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator("[А-ЯЁа-яё, ]+$")
                        ],
                        verbose_name="name",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="Subcategory's slug", verbose_name="slug"
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        help_text="Subcategory's image",
                        upload_to="media/subcategory",
                        verbose_name="image",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        help_text="Subcategory's category",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subcategories",
                        to="products.category",
                        verbose_name="category",
                    ),
                ),
            ],
            options={
                "verbose_name": "subcategory",
                "verbose_name_plural": "subcategories",
            },
        ),
        migrations.AddConstraint(
            model_name="subcategory",
            constraint=models.UniqueConstraint(
                fields=("name", "category"), name="unique_subcategory_category_together"
            ),
        ),
    ]
