# Generated by Django 4.2.5 on 2023-09-29 12:38

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import products.validators


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Subcategory's name",
                        max_length=150,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                "[a-zA-zА-ЯЁа-яё0-9, ]+$"
                            )
                        ],
                        verbose_name="name",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(help_text="Product's slug", verbose_name="slug"),
                ),
                (
                    "image_small",
                    models.ImageField(
                        help_text="Product's small image",
                        upload_to="media/product/small",
                        validators=[
                            products.validators.ImageWidthHeightValidator(
                                max_height=200, max_width=200
                            )
                        ],
                        verbose_name="small image",
                    ),
                ),
                (
                    "image_medium",
                    models.ImageField(
                        help_text="Product's medium image",
                        upload_to="media/product/medium",
                        validators=[
                            products.validators.ImageWidthHeightValidator(
                                max_height=400, max_width=400
                            )
                        ],
                        verbose_name="medium image",
                    ),
                ),
                (
                    "image_large",
                    models.ImageField(
                        help_text="Product's large image",
                        upload_to="media/product/large",
                        validators=[
                            products.validators.ImageWidthHeightValidator(
                                max_height=600, max_width=600
                            )
                        ],
                        verbose_name="medium image",
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Product's price",
                        max_digits=10,
                        verbose_name="price",
                    ),
                ),
                (
                    "subcategory",
                    models.ForeignKey(
                        help_text="product's subcategory",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="products",
                        to="products.subcategory",
                        verbose_name="subcategory",
                    ),
                ),
            ],
            options={
                "verbose_name": "product",
                "verbose_name_plural": "products",
            },
        ),
        migrations.AddConstraint(
            model_name="product",
            constraint=models.UniqueConstraint(
                fields=("name", "subcategory"),
                name="unique_product_subcategory_together",
            ),
        ),
    ]
