# Generated by Django 4.2.5 on 2023-09-30 08:16

from django.db import migrations, models
import products.validators


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0002_product_product_unique_product_subcategory_together"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="image_large",
            field=models.ImageField(
                help_text="Product's large image",
                upload_to="media/product/large",
                validators=[
                    products.validators.ImageWidthHeightValidator(
                        max_height=600, max_width=600
                    )
                ],
                verbose_name="large image",
            ),
        ),
    ]
